# Generated by Django 3.2.4 on 2021-06-18 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AppUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Username', models.CharField(default='', max_length=70)),
                ('email', models.CharField(default='', max_length=200)),
                ('mobile', models.CharField(default=False, max_length=10)),
            ],
        ),
    ]
